export interface StockFundamentals {
  symbol: string;
  name: string;
  sector: string;
  currentPrice: number;
  pe: number;
  pb: number;
  roe: number;
  debtToEquity: number;
  revenueGrowth: number;
  profitGrowth: number;
  dividendYield: number;
  marketCap: number;
  momentumScore: number; // 0-100
  trend: "bullish" | "neutral" | "bearish";
  yearReturn: number;
}

export const BENCHMARKS = {
  nifty50: {
    name: "NIFTY 50",
    yearReturn: 12.4,
    threeYearCagr: 14.2,
    fiveYearCagr: 13.8,
    volatility: 15.2,
    sharpeRatio: 0.82,
  },
  sensex: {
    name: "SENSEX",
    yearReturn: 11.9,
    threeYearCagr: 13.6,
    fiveYearCagr: 13.2,
    volatility: 14.8,
    sharpeRatio: 0.79,
  },
};

export const STOCK_DATABASE: Record<string, StockFundamentals> = {
  RELIANCE: {
    symbol: "RELIANCE",
    name: "Reliance Industries",
    sector: "Energy",
    currentPrice: 2850,
    pe: 28.5,
    pb: 2.1,
    roe: 9.8,
    debtToEquity: 0.35,
    revenueGrowth: 8.2,
    profitGrowth: 12.5,
    dividendYield: 0.35,
    marketCap: 1920000,
    momentumScore: 72,
    trend: "bullish",
    yearReturn: 18.4,
  },
  TCS: {
    symbol: "TCS",
    name: "Tata Consultancy Services",
    sector: "IT",
    currentPrice: 4120,
    pe: 32.1,
    pb: 12.5,
    roe: 48.2,
    debtToEquity: 0.05,
    revenueGrowth: 7.5,
    profitGrowth: 9.2,
    dividendYield: 1.4,
    marketCap: 1480000,
    momentumScore: 65,
    trend: "neutral",
    yearReturn: 8.2,
  },
  HDFCBANK: {
    symbol: "HDFCBANK",
    name: "HDFC Bank",
    sector: "Banking",
    currentPrice: 1720,
    pe: 19.8,
    pb: 2.8,
    roe: 16.5,
    debtToEquity: 0,
    revenueGrowth: 15.2,
    profitGrowth: 18.1,
    dividendYield: 1.1,
    marketCap: 1320000,
    momentumScore: 78,
    trend: "bullish",
    yearReturn: 22.1,
  },
  INFY: {
    symbol: "INFY",
    name: "Infosys",
    sector: "IT",
    currentPrice: 1890,
    pe: 28.4,
    pb: 8.2,
    roe: 31.5,
    debtToEquity: 0.02,
    revenueGrowth: 5.8,
    profitGrowth: 6.5,
    dividendYield: 2.1,
    marketCap: 785000,
    momentumScore: 58,
    trend: "neutral",
    yearReturn: 5.4,
  },
  ICICIBANK: {
    symbol: "ICICIBANK",
    name: "ICICI Bank",
    sector: "Banking",
    currentPrice: 1285,
    pe: 18.2,
    pb: 3.1,
    roe: 17.8,
    debtToEquity: 0,
    revenueGrowth: 18.5,
    profitGrowth: 22.3,
    dividendYield: 0.8,
    marketCap: 910000,
    momentumScore: 82,
    trend: "bullish",
    yearReturn: 28.5,
  },
  BHARTIARTL: {
    symbol: "BHARTIARTL",
    name: "Bharti Airtel",
    sector: "Telecom",
    currentPrice: 1580,
    pe: 42.5,
    pb: 8.5,
    roe: 12.2,
    debtToEquity: 1.85,
    revenueGrowth: 12.8,
    profitGrowth: 45.2,
    dividendYield: 0.5,
    marketCap: 895000,
    momentumScore: 85,
    trend: "bullish",
    yearReturn: 35.2,
  },
  ITC: {
    symbol: "ITC",
    name: "ITC Limited",
    sector: "FMCG",
    currentPrice: 465,
    pe: 28.8,
    pb: 7.2,
    roe: 28.5,
    debtToEquity: 0.01,
    revenueGrowth: 6.2,
    profitGrowth: 8.5,
    dividendYield: 3.2,
    marketCap: 580000,
    momentumScore: 55,
    trend: "neutral",
    yearReturn: 12.8,
  },
  SBIN: {
    symbol: "SBIN",
    name: "State Bank of India",
    sector: "Banking",
    currentPrice: 820,
    pe: 10.5,
    pb: 1.45,
    roe: 16.2,
    debtToEquity: 0,
    revenueGrowth: 12.5,
    profitGrowth: 28.5,
    dividendYield: 1.8,
    marketCap: 735000,
    momentumScore: 75,
    trend: "bullish",
    yearReturn: 42.5,
  },
  HINDUNILVR: {
    symbol: "HINDUNILVR",
    name: "Hindustan Unilever",
    sector: "FMCG",
    currentPrice: 2380,
    pe: 58.2,
    pb: 12.8,
    roe: 22.5,
    debtToEquity: 0.02,
    revenueGrowth: 3.5,
    profitGrowth: 5.2,
    dividendYield: 1.6,
    marketCap: 560000,
    momentumScore: 42,
    trend: "bearish",
    yearReturn: -2.5,
  },
  KOTAKBANK: {
    symbol: "KOTAKBANK",
    name: "Kotak Mahindra Bank",
    sector: "Banking",
    currentPrice: 1785,
    pe: 22.5,
    pb: 2.5,
    roe: 14.2,
    debtToEquity: 0,
    revenueGrowth: 10.2,
    profitGrowth: 12.8,
    dividendYield: 0.15,
    marketCap: 355000,
    momentumScore: 62,
    trend: "neutral",
    yearReturn: 15.2,
  },
  LT: {
    symbol: "LT",
    name: "Larsen & Toubro",
    sector: "Infrastructure",
    currentPrice: 3580,
    pe: 35.2,
    pb: 5.8,
    roe: 15.8,
    debtToEquity: 0.65,
    revenueGrowth: 18.5,
    profitGrowth: 22.1,
    dividendYield: 0.85,
    marketCap: 495000,
    momentumScore: 80,
    trend: "bullish",
    yearReturn: 38.5,
  },
  AXISBANK: {
    symbol: "AXISBANK",
    name: "Axis Bank",
    sector: "Banking",
    currentPrice: 1125,
    pe: 13.8,
    pb: 1.85,
    roe: 15.5,
    debtToEquity: 0,
    revenueGrowth: 14.2,
    profitGrowth: 18.5,
    dividendYield: 0.1,
    marketCap: 348000,
    momentumScore: 70,
    trend: "bullish",
    yearReturn: 25.8,
  },
  WIPRO: {
    symbol: "WIPRO",
    name: "Wipro",
    sector: "IT",
    currentPrice: 285,
    pe: 22.5,
    pb: 3.2,
    roe: 16.8,
    debtToEquity: 0.08,
    revenueGrowth: 2.5,
    profitGrowth: 4.2,
    dividendYield: 2.8,
    marketCap: 152000,
    momentumScore: 38,
    trend: "bearish",
    yearReturn: -8.5,
  },
  MARUTI: {
    symbol: "MARUTI",
    name: "Maruti Suzuki",
    sector: "Auto",
    currentPrice: 12450,
    pe: 28.5,
    pb: 4.8,
    roe: 16.2,
    debtToEquity: 0.02,
    revenueGrowth: 12.5,
    profitGrowth: 15.8,
    dividendYield: 0.9,
    marketCap: 392000,
    momentumScore: 68,
    trend: "bullish",
    yearReturn: 18.2,
  },
  SUNPHARMA: {
    symbol: "SUNPHARMA",
    name: "Sun Pharmaceutical",
    sector: "Pharma",
    currentPrice: 1820,
    pe: 38.5,
    pb: 5.2,
    roe: 14.5,
    debtToEquity: 0.12,
    revenueGrowth: 10.5,
    profitGrowth: 15.2,
    dividendYield: 0.7,
    marketCap: 438000,
    momentumScore: 72,
    trend: "bullish",
    yearReturn: 22.5,
  },
};

export function getStockData(symbol: string): StockFundamentals | null {
  const normalized = symbol.toUpperCase().replace(/\.(NS|BO|NSE|BSE)$/i, "");
  return STOCK_DATABASE[normalized] || null;
}

export function enrichHolding(symbol: string, avgPrice: number) {
  const stock = getStockData(symbol);
  if (stock) {
    return {
      symbol: stock.symbol,
      name: stock.name,
      sector: stock.sector,
      currentPrice: stock.currentPrice,
      fundamentals: stock,
    };
  }
  // Fallback for unknown symbols
  const estimatedPrice = avgPrice * (1 + (Math.random() * 0.3 - 0.1));
  return {
    symbol: symbol.toUpperCase(),
    name: symbol.toUpperCase(),
    sector: "Unknown",
    currentPrice: Math.round(estimatedPrice * 100) / 100,
    fundamentals: null,
  };
}
